### ISSUE TITLE
List of supported hardware?

### ISSUE THREAD

**Issue by SheetLightning** [arduino-libraries/TFT#40]
Which displays is this library compatible with? I am looking for a library compatible with SSD1963 displays and wondered whether this is supported? Is it supported on the ESP8266 and ESP32?

Would it not be helpful to have a list of supported hardware somewhere?

**Comment by per1234** [comment]
Hi @SheetLightning. Thanks for your suggestion. The supported displays are documented on the library reference page:
https://www.arduino.cc/reference/en/libraries/tft/

>This library is compatible with most of the TFT display based on the ST7735 chipset.

**Comment by SheetLightning** [comment]
I am asking about apples and you answer about oranges. I am asking about the SSD1963chip, not the ST7735 chipset? I already know that the ST7735 is supported, but I see nothing about the SSD1963?

**Comment by per1234** [comment]
> I see nothing about the SSD1963?

That is because it is not supported. ST7735-based displays are supported. Displays of any other type are not supported. There is no point in Arduino attempting to list every display which is not supported.

For other display types, please search the [Arduino Library Manager](https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries#using-the-library-manager). Many additional displays are supported by the thousands of libraries listed there.
